# Form implementation generated from reading ui file 'view/viewGrafica.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Grafica(object):
    def setupUi(self, Grafica):
        Grafica.setObjectName("Grafica")
        Grafica.resize(633, 488)
        self.centralwidget = QtWidgets.QWidget(parent=Grafica)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 611, 411))
        self.graphicsView.setObjectName("graphicsView")
        self.buscarGrafica = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buscarGrafica.setGeometry(QtCore.QRect(350, 430, 80, 25))
        self.buscarGrafica.setObjectName("buscarGrafica")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 430, 49, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 430, 45, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.FechaGraficaDesde = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.FechaGraficaDesde.setGeometry(QtCore.QRect(60, 430, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.FechaGraficaDesde.setFont(font)
        self.FechaGraficaDesde.setCalendarPopup(True)
        self.FechaGraficaDesde.setObjectName("FechaGraficaDesde")
        self.FechaGraficaHasta = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.FechaGraficaHasta.setGeometry(QtCore.QRect(230, 430, 111, 29))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.FechaGraficaHasta.setFont(font)
        self.FechaGraficaHasta.setCalendarPopup(True)
        self.FechaGraficaHasta.setObjectName("FechaGraficaHasta")
        self.salirGrafica = QtWidgets.QPushButton(parent=self.centralwidget)
        self.salirGrafica.setGeometry(QtCore.QRect(540, 430, 80, 25))
        self.salirGrafica.setObjectName("salirGrafica")
        Grafica.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=Grafica)
        self.statusbar.setObjectName("statusbar")
        Grafica.setStatusBar(self.statusbar)

        self.retranslateUi(Grafica)
        QtCore.QMetaObject.connectSlotsByName(Grafica)

    def retranslateUi(self, Grafica):
        _translate = QtCore.QCoreApplication.translate
        Grafica.setWindowTitle(_translate("Grafica", "MainWindow"))
        self.buscarGrafica.setText(_translate("Grafica", "Buscar"))
        self.label_5.setText(_translate("Grafica", "Desde:"))
        self.label_4.setText(_translate("Grafica", "Hasta:"))
        self.FechaGraficaDesde.setDisplayFormat(_translate("Grafica", "dd/MM/yyyy"))
        self.FechaGraficaHasta.setDisplayFormat(_translate("Grafica", "dd/MM/yyyy"))
        self.salirGrafica.setText(_translate("Grafica", "Salir"))
from pyqtgraph import PlotWidget
